; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-wroom-02]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

; --- Flash Settings ---
board_build.flash_mode = dio
board_build.f_flash = 80000000L
board_build.filesystem = littlefs
board_build.partitions = default.csv # if default is too small, in the future we can use min_spiffs.csv to reduce the size of the SPIFFS partition, as we only need to store a few files

; --- USB & Debug ---
monitor_speed = 115200
build_flags = 
	-D BUILD_TAG=\"${sysenv.FIRMWARE_VERSION}\"
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

; --- Dependencies ---
lib_deps = 
	bblanchon/ArduinoJson@^7.4.2
	https://github.com/tzapu/WiFiManager.git#4131fe617d01d746677e8b909379597162c2ca58
	adafruit/Adafruit NeoPixel@^1.15.2

board_build.embed_txtfiles = 
    src/web/index.html
	src/web/index.js
    src/web/configuration.html
    src/web/configuration.js
    src/web/common.js
    src/web/common.css
