name: Firmware Build release

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build:
    name: Build firmware bin and attach it to the release
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Cache pip
        uses: actions/cache@v5
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache PlatformIO
        uses: actions/cache@v5
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-platformio

      - name: Set up Python
        uses: actions/setup-python@v6

      - name: Install PlatformIO
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -U platformio

      - name: Run PlatformIO Build
        working-directory: firmware
        env:
          FIRMWARE_VERSION: ${{ github.ref_name }}
        run: pio run -e esp32-c3-wroom-02

      - name: Upload Firmware to Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: firmware/.pio/build/esp32-c3-wroom-02/firmware.bin
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}