name: Firmware Build release

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build:
    name: Build firmware bin and attach it to the release
    runs-on: ubuntu-latest
    if: startsWith(github.event.release.tag_name, 'firmware-') || github.event_name == 'workflow_dispatch'

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Cache pip
        uses: actions/cache@v5
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache PlatformIO
        uses: actions/cache@v5
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-platformio

      - name: Set up Python
        uses: actions/setup-python@v6

      - name: Install PlatformIO
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -U platformio

      - name: Run PlatformIO Build
        working-directory: firmware
        env:
          FIRMWARE_VERSION: ${{ github.ref_name }}
        run: pio run -e esp32-c3-wroom-02

      - name: Upload Firmware to Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: firmware/.pio/build/esp32-c3-wroom-02/firmware.bin
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Generate Firmware Manifest
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mkdir -p manifest
          cat <<EOF > manifest/latest_firmware.json
          {
            "version": "${{ github.ref_name }}",
            "url": "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/firmware.bin"
          }
          EOF

      - name: Setup GitHub Pages
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/configure-pages@v5

      - name: Upload Pages Artifact
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-pages-artifact@v3
        with:
          path: './manifest'

      - name: Deploy to GitHub Pages
        if: startsWith(github.ref, 'refs/tags/')
        id: deployment
        uses: actions/deploy-pages@v4